import { Router } from "express";
import { authMiddleware, requireAdmin } from "./middlewares/auth.middleware";
import { AuthController } from "./controllers/auth.controller";
import { UserController } from "./controllers/user.controller";
import { MesaController } from "./controllers/mesa.controller";
import { ClienteController } from "./controllers/cliente.controller";
import { PratoController } from "./controllers/prato.controller";
import { PedidoController } from "./controllers/pedido.controller";

const router=Router();
const auth=new AuthController(),users=new UserController(),mesas=new MesaController(),clientes=new ClienteController(),pratos=new PratoController(),pedidos=new PedidoController();
router.get("/health",(_req,res)=>res.json({ok:true,service:"meta-restaurante-api",timestamp:new Date().toISOString()}));
router.post("/login",auth.login.bind(auth));
router.use(authMiddleware);
router.get("/me",auth.me.bind(auth));router.post("/logout",auth.logout.bind(auth));
router.get("/mesas",mesas.list.bind(mesas));router.get("/mesas/:id",mesas.get.bind(mesas));router.post("/mesas",mesas.create.bind(mesas));router.put("/mesas/:id",mesas.update.bind(mesas));router.delete("/mesas/:id",mesas.delete.bind(mesas));
router.get("/clientes",clientes.list.bind(clientes));router.get("/clientes/:id",clientes.get.bind(clientes));router.post("/clientes",clientes.create.bind(clientes));router.put("/clientes/:id",clientes.update.bind(clientes));router.delete("/clientes/:id",clientes.delete.bind(clientes));
router.get("/cardapio",pratos.list.bind(pratos));router.get("/cardapio/:id",pratos.get.bind(pratos));router.post("/cardapio",pratos.create.bind(pratos));router.put("/cardapio/:id",pratos.update.bind(pratos));router.delete("/cardapio/:id",pratos.delete.bind(pratos));
router.get("/pedidos",pedidos.list.bind(pedidos));router.post("/pedidos",pedidos.create.bind(pedidos));router.put("/pedidos/:id",pedidos.update.bind(pedidos));router.delete("/pedidos/:id",pedidos.delete.bind(pedidos));
router.use("/usuarios",requireAdmin);router.get("/usuarios",users.list.bind(users));router.post("/usuarios",users.create.bind(users));router.put("/usuarios/:id",users.update.bind(users));router.delete("/usuarios/:id",users.delete.bind(users));
export default router;
