ALTER TYPE "Role" RENAME VALUE 'PESQUISADOR' TO 'ATENDENTE';
CREATE TYPE "TableStatus" AS ENUM ('DISPONIVEL', 'OCUPADA', 'RESERVADA');
CREATE TYPE "OrderStatus" AS ENUM ('PENDENTE', 'PREPARANDO', 'PRONTO', 'ENTREGUE');
ALTER TABLE "eventos" RENAME TO "pratos";
ALTER TABLE "pratos" RENAME COLUMN "local" TO "categoria";
ALTER TABLE "pratos" DROP COLUMN "data_inicio";
ALTER TABLE "pratos" DROP COLUMN "data_fim";
ALTER TABLE "pratos" ADD COLUMN "preco" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "turmas" RENAME TO "mesas";
ALTER TABLE "mesas" RENAME COLUMN "ano_escolar" TO "lugares";
ALTER TABLE "mesas" ALTER COLUMN "lugares" TYPE INTEGER USING CASE WHEN COALESCE("lugares", '') ~ '^[0-9]+$' THEN "lugares"::INTEGER ELSE 2 END;
UPDATE "mesas" SET "lugares"=2 WHERE "lugares" IS NULL;
ALTER TABLE "mesas" ALTER COLUMN "lugares" SET NOT NULL;
ALTER TABLE "mesas" RENAME COLUMN "escola" TO "status";
UPDATE "mesas" SET "status" = CASE lower(COALESCE("status", '')) WHEN 'ocupada' THEN 'OCUPADA' WHEN 'reservada' THEN 'RESERVADA' ELSE 'DISPONIVEL' END;
ALTER TABLE "mesas" ALTER COLUMN "status" SET DEFAULT 'DISPONIVEL';
ALTER TABLE "mesas" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "mesas" ALTER COLUMN "status" TYPE "TableStatus" USING "status"::"TableStatus";
ALTER TABLE "mesas" ALTER COLUMN "status" SET DEFAULT 'DISPONIVEL';
ALTER TABLE "estudantes" RENAME TO "clientes";
ALTER TABLE "clientes" DROP CONSTRAINT "estudantes_turma_id_fkey";
DROP INDEX IF EXISTS "estudantes_turma_id_idx";
ALTER TABLE "clientes" DROP COLUMN "idade";
ALTER TABLE "clientes" DROP COLUMN "profissao_futura";
ALTER TABLE "clientes" DROP COLUMN "turma_id";
ALTER TABLE "clientes" ADD COLUMN "telefone" TEXT;
ALTER TABLE "clientes" ADD COLUMN "email" TEXT;
DROP INDEX "pesquisas_campo_evento_id_estudante_id_key";
ALTER TABLE "pesquisas_campo" DROP CONSTRAINT "pesquisas_campo_evento_id_fkey";
ALTER TABLE "pesquisas_campo" DROP CONSTRAINT "pesquisas_campo_estudante_id_fkey";
ALTER TABLE "pesquisas_campo" RENAME TO "pedidos";
ALTER TABLE "pedidos" RENAME COLUMN "evento_id" TO "prato_id";
ALTER TABLE "pedidos" RENAME COLUMN "estudante_id" TO "cliente_id";
ALTER TABLE "pedidos" ADD COLUMN "mesa_id" TEXT;
ALTER TABLE "pedidos" ADD COLUMN "status" "OrderStatus" NOT NULL DEFAULT 'PENDENTE';
ALTER TABLE "pedidos" ADD COLUMN "total" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "pedidos" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "pedidos" RENAME COLUMN "prato_id" TO "legacy_prato_id";
CREATE TABLE "itens_pedido" ("id" TEXT NOT NULL, "pedido_id" TEXT NOT NULL, "prato_id" TEXT NOT NULL, "quantidade" INTEGER NOT NULL DEFAULT 1, "preco_unitario" DECIMAL(10,2) NOT NULL DEFAULT 0, CONSTRAINT "itens_pedido_pkey" PRIMARY KEY ("id"));
INSERT INTO "itens_pedido" ("id", "pedido_id", "prato_id", "quantidade", "preco_unitario") SELECT md5(random()::text || clock_timestamp()::text), p."id", p."legacy_prato_id", 1, d."preco" FROM "pedidos" p JOIN "pratos" d ON d."id"=p."legacy_prato_id";
UPDATE "pedidos" p SET "total"=d."preco" FROM "pratos" d WHERE d."id"=p."legacy_prato_id";
ALTER TABLE "pedidos" DROP COLUMN "legacy_prato_id";
ALTER TABLE "pedidos" ADD CONSTRAINT "pedidos_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "pedidos" ADD CONSTRAINT "pedidos_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "pedidos" ADD CONSTRAINT "pedidos_mesa_id_fkey" FOREIGN KEY ("mesa_id") REFERENCES "mesas"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "itens_pedido" ADD CONSTRAINT "itens_pedido_pedido_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "itens_pedido" ADD CONSTRAINT "itens_pedido_prato_id_fkey" FOREIGN KEY ("prato_id") REFERENCES "pratos"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "itens_pedido_pedido_id_idx" ON "itens_pedido"("pedido_id");
CREATE INDEX "itens_pedido_prato_id_idx" ON "itens_pedido"("prato_id");
DROP INDEX IF EXISTS "pesquisas_campo_evento_id_idx";
DROP INDEX IF EXISTS "pesquisas_campo_estudante_id_idx";
ALTER TABLE "pedidos" DROP CONSTRAINT "pesquisas_campo_usuario_id_fkey";
DROP INDEX IF EXISTS "pesquisas_campo_usuario_id_idx";
ALTER TABLE "pratos" RENAME CONSTRAINT "eventos_pkey" TO "pratos_pkey";
ALTER TABLE "mesas" RENAME CONSTRAINT "turmas_pkey" TO "mesas_pkey";
ALTER TABLE "clientes" RENAME CONSTRAINT "estudantes_pkey" TO "clientes_pkey";
ALTER TABLE "pedidos" RENAME CONSTRAINT "pesquisas_campo_pkey" TO "pedidos_pkey";
